# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
                ('country_currency_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='channel_cc_id', to='business.CountryCurrency')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_on', models.CharField(max_length=4, verbose_name='Expired On')),
                ('card_holder_name', models.CharField(max_length=80, verbose_name='Card Holder Name')),
                ('cvv_number', models.CharField(max_length=4, verbose_name='CVV Number')),
                ('cc_number', models.CharField(max_length=16, unique=True, verbose_name='Credit Card Number')),
                ('status_cc', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('status_cc_type', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('status_phone', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('card_id', models.BigIntegerField(default=1, verbose_name='Card Id')),
                ('pin', models.BigIntegerField(default=None, null=True, verbose_name='Pin')),
                ('sms_verified', models.SmallIntegerField(default=None, null=True, verbose_name='Sms Verified')),
                ('city', models.CharField(blank=True, max_length=280, null=True, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code')),
                ('address_line1', models.CharField(blank=True, max_length=280, null=True, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=280, null=True, verbose_name='Address Line 2')),
                ('signup_token', models.CharField(max_length=280, null=True, verbose_name='Signup Token')),
                ('sifts_last_update', models.DateField(default=django.utils.timezone.now, verbose_name='Sifts Update')),
                ('sifts_score', models.FloatField(default=0.0, verbose_name='Sifts Score')),
                ('status_profile', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
                ('channel_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='profile_channel_id', to='customer.Channel')),
                ('country_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='country_profile_id', to='business.Country')),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='profile_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='phone_profile_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='cc_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cc_cct_id', to='customer.CreditCardType'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='profile_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='profile_cc_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
