# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_id',
            field=models.CharField(default=None, max_length=80, null=True, verbose_name='Card Id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(default=None, max_length=80, null=True, verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sms_verified',
            field=models.BooleanField(default=False, verbose_name='Sms Verified'),
        ),
    ]
