# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20170117_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expired_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
