# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20170117_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressline',
            name='detail',
            field=models.TextField(verbose_name='Detail'),
        ),
    ]
