# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20170117_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='channel_id',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='country_id',
            new_name='country',
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile'),
        ),
    ]
