# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20170210_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cvv_number',
            field=models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='CVV Number'),
        ),
    ]
