# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credit_card_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='payment_cc_id', to='customer.CreditCard'),
        ),
        migrations.AddField(
            model_name='payment',
            name='method_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='payment_method_id', to='business.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='currency',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='business.Country'),
        ),
        migrations.AddField(
            model_name='countrycurrency',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_id', to='business.Country'),
        ),
        migrations.AddField(
            model_name='countrycurrency',
            name='currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_id', to='business.Currency'),
        ),
    ]
