# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20170120_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='credit_card_id',
            new_name='credit_card',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='method_id',
            new_name='method',
        ),
    ]
