# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20170120_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='next_transaction_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='next_unit_day',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Next Unit Day'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_payment_id', to='business.Payment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='related_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_related_id', to='business.Transaction'),
        ),
    ]
