# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0006_auto_20170120_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_transaction', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
