# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_code',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Transaction Code'),
        ),
    ]
