# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20170120_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_country_id', to='business.Country'),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_operator_id', to='business.Operator'),
        ),
    ]
