# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20170131_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='country',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='operator',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
